print(number("55"))
print(number("55.5"))
print(number(42))
print(boolean("true"))
print(boolean("false"))
print(boolean(true))
print(boolean(false))
print(array("[1, 2, 3]"))
print(array(["a", "b"]))
print(record("{\"x\":1, \"y\":2}"))
print(record({name:"test", value:42}))
