print(keys({x:1, y:2}))
print(keys({}))
print(values({x:1, y:2}))
print(values({}))
print(has({x:1}, "x"))
print(has({x:1}, "z"))
print(has({}, "x"))
print(remove_key({x:1, y:2}, "x"))
print(remove_key({x:1, y:2}, "z"))
print(remove_key({}, "x"))
