print(left("abcdef", 2))
print(right("abcdef", 3))
print(mid("abcdef", 2, 3))
print(mid("abcdef", 2, 3, "XYZ"))
print(left("abc", 10))
print(right("abc", 10))
print(mid("abc", 1, 10))
print(mid("abc", 10, 2))
print(mid("abc", 10, 2, "XYZ"))
