print(replace("hello", "l", "x"))
print(replace("hello world", "o", "0"))
print(replace("abc", "x", "y"))
print(starts_with("hello", "he"))
print(starts_with("hello", "lo"))
print(starts_with("hello", ""))
print(ends_with("hello", "lo"))
print(ends_with("hello", "he"))
print(ends_with("hello", ""))
print(repeat("ha", 3))
print(repeat("x", 1))
print(repeat("test", 0))
