print(type(55))
print(type("hello"))
print(type(true))
print(type([1, 2]))
print(type({x:1}))
print(type(nothing))
print(type(unknown))

print(is_string("hello"))
print(is_string(55))
print(is_number(55))
print(is_number("55"))
print(is_boolean(true))
print(is_boolean(false))
print(is_array([1, 2]))
print(is_array({x:1}))
print(is_record({x:1}))
print(is_record([1, 2]))
print(is_nothing(nothing))
print(is_nothing(0))
print(is_unknown(unknown))
print(is_unknown(nothing))
