' Phase 2: codepoint-aware character ops + \u{...} escape.
print(len("café"))
print(byte_count("café"))
print(left("café", 3))
print(right("café", 2))
print(mid("café", 3, 1))
print(mid("héllo", 1, 3))
print(reverse("café"))
print(reverse("a😀b"))
print(find("héllo", "llo"))
print(find("héllo", "z") = nothing)
print(mid("café", 0, 2, "XX"))
print("\u{1F600}")
print(len("\u{1F600}"))
print("caf\u{e9}" = "café")
print(len("a\u{1F600}b"))
