create table if not exists gbasic_site_pages (
    slug text primary key,
    title text not null,
    body text not null,
    published boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists gbasic_site_users (
    id integer generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    password_algorithm text not null,
    admin boolean not null default false,
    disabled boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists gbasic_site_sessions (
    id text primary key,
    user_id integer not null references gbasic_site_users(id) on delete cascade,
    csrf_token text not null,
    created_at timestamp not null default current_timestamp,
    expires_at timestamp not null,
    revoked_at timestamp
);

create table if not exists gbasic_site_categories (
    id integer generated by default as identity primary key,
    slug text not null unique,
    title text not null,
    description text not null default '',
    hidden boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists gbasic_site_topics (
    id integer generated by default as identity primary key,
    category_id integer not null references gbasic_site_categories(id) on delete cascade,
    title text not null,
    author_name text not null,
    body text not null,
    hidden boolean not null default false,
    locked boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

alter table gbasic_site_topics
    add column if not exists moderated_at timestamp,
    add column if not exists moderated_by text;

create table if not exists gbasic_site_posts (
    id integer generated by default as identity primary key,
    topic_id integer not null references gbasic_site_topics(id) on delete cascade,
    author_name text not null,
    body text not null,
    hidden boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

alter table gbasic_site_posts
    add column if not exists moderated_at timestamp,
    add column if not exists moderated_by text;
