create table if not exists gbasic_site_pages (
    slug text primary key,
    title text not null,
    body text not null,
    published boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists gbasic_site_categories (
    id integer generated by default as identity primary key,
    slug text not null unique,
    title text not null,
    description text not null default '',
    hidden boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists gbasic_site_topics (
    id integer generated by default as identity primary key,
    category_id integer not null references gbasic_site_categories(id) on delete cascade,
    title text not null,
    author_name text not null,
    body text not null,
    hidden boolean not null default false,
    locked boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table if not exists gbasic_site_posts (
    id integer generated by default as identity primary key,
    topic_id integer not null references gbasic_site_topics(id) on delete cascade,
    author_name text not null,
    body text not null,
    hidden boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);
