#!/usr/bin/env python3
"""Generate src/currency_table.h from the system's ISO 4217 data.

Run when the currency list needs refreshing:
    python3 tools/make_currency_table.py > src/currency_table.h

The OUTPUT IS COMMITTED, so a build never depends on iso-codes being
installed -- and so a currency cannot silently appear or vanish depending on
the build machine, which for a money type would be a correctness problem
rather than a packaging one.

iso-codes ships alpha/numeric codes but NOT minor units, so the exponents come
from the ISO 4217 rules below. They are stable and short enough to state
outright, which is better than a second data file that could drift from the
first.
"""
import json, sys

# ISO 4217 minor units. Everything not listed has two.
ZERO = {"BIF","CLP","DJF","GNF","ISK","JPY","KMF","KRW","PYG","RWF","UGX",
        "UYI","VND","VUV","XAF","XOF","XPF",
        # Metals, special and fund codes have no minor unit at all.
        "XAG","XAU","XBA","XBB","XBC","XBD","XDR","XPD","XPT","XSU","XTS",
        "XUA","XXX"}
THREE = {"BHD","IQD","JOD","KWD","LYD","OMR","TND"}
FOUR  = {"CLF","UYW"}

def exponent(code):
    if code in ZERO:  return 0
    if code in THREE: return 3
    if code in FOUR:  return 4
    return 2

rows = json.load(open("/usr/share/iso-codes/json/iso_4217.json"))["4217"]
rows.sort(key=lambda r: r["alpha_3"])

out = sys.stdout.write
out("/* GENERATED by tools/make_currency_table.py -- do not edit by hand.\n"
    " *\n"
    " * ISO 4217 currency codes with their minor-unit exponents. Committed\n"
    " * rather than read at build time so a build never depends on iso-codes\n"
    " * being installed, and so a currency cannot appear or vanish depending on\n"
    " * the build machine -- for a money type that would be a correctness\n"
    " * problem, not a packaging one.\n"
    " *\n"
    " * Storage scale for a currency is `exponent + MONEY_GUARD_DIGITS`; see\n"
    " * docs/money_design.md section 3.\n"
    " */\n\n")
out("typedef struct {\n"
    "    const char *alpha;      /* ISO 4217 three-letter code */\n"
    "    unsigned short numeric; /* ISO 4217 numeric code */\n"
    "    unsigned char exponent; /* minor-unit digits */\n"
    "} CurrencyDef;\n\n")
out("static const CurrencyDef currency_table[] = {\n")
for r in rows:
    out('    { "%s", %3d, %d },\n' % (r["alpha_3"], int(r["numeric"]), exponent(r["alpha_3"])))
out("};\n\n")
out("#define CURRENCY_TABLE_COUNT %d\n" % len(rows))
