#!/usr/bin/env bash
# Regenerate tests/libcurl_floor/symbols.txt: every libcurl identifier that
# EXISTS at the release tarball's build floor.
#
# WHY A COMMITTED LIST RATHER THAN A BUILD. The floor is ubuntu:22.04 --
# tools/build-release-tarball.sh picks it for its glibc, and that same image
# carries libcurl 7.81.0. A development machine is always newer (8.18.0 here),
# so a symbol added after the floor compiles fine on every machine anybody
# works on and breaks the only machine that matters. Building in the container
# catches it and needs podman, a network and two minutes; comparing against a
# list catches the same thing in milliseconds with nothing installed, which is
# what lets it sit in the routine gate instead of a manual tier.
#
# The list is GENERATED, never hand-edited: a fixture nothing can reproduce is
# a fixture that tests itself. Re-run this only when the floor deliberately
# moves, and say so in the commit.
set -euo pipefail
cd "$(dirname "$0")/.."

IMAGE="${IMAGE:-docker.io/library/ubuntu:22.04}"
OUT=tests/libcurl_floor/symbols.txt

runtime=""
for c in podman docker; do command -v "$c" >/dev/null 2>&1 && { runtime="$c"; break; }; done
[ -n "$runtime" ] || { echo "FAIL: need podman or docker" >&2; exit 1; }

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

"$runtime" run --rm "$IMAGE" bash -c '
set -eu
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq >/dev/null 2>&1
apt-get install -y -qq libcurl4-openssl-dev >/dev/null 2>&1
ver=$(sed -n "s/.*define LIBCURL_VERSION \"\\(.*\\)\"/\\1/p" /usr/include/*/curl/curlver.h /usr/include/curl/curlver.h 2>/dev/null | head -1)
num=$(sed -n "s/.*define LIBCURL_VERSION_NUM \\(0x[0-9a-fA-F]*\\).*/\\1/p" /usr/include/*/curl/curlver.h /usr/include/curl/curlver.h 2>/dev/null | head -1)
echo "# libcurl $ver ($num) -- the version in the release tarball base image"
cat /usr/include/*/curl/*.h /usr/include/curl/*.h 2>/dev/null \
  | grep -oE "\\b(LIBCURL|CURL)[A-Za-z0-9_]*" | sort -u
' > "$tmp"

mkdir -p "$(dirname "$OUT")"
{
    echo "# GENERATED by tools/make_libcurl_floor_symbols.sh -- do not hand-edit."
    echo "# Every libcurl identifier available at the release build floor."
    echo "# A name NOT in this list may be used only inside a"
    echo "# \`#if LIBCURL_VERSION_NUM >= ...\` guard; tests/run_libcurl_floor.sh"
    echo "# is what enforces that."
    cat "$tmp"
} > "$OUT"

echo "wrote $OUT ($(grep -cv '^#' "$OUT") symbols)"
