#!/usr/bin/env python3
"""Build examples/fixtures/xlsx/shared.xlsx -- the shared-formula fixture.

WHAT A SHARED FORMULA IS. Excel does not repeat a formula filled down a column.
It writes the text once on the anchor cell:

    <c r="C2"><f t="shared" ref="C2:C6" si="0">A2*$B$1</f><v>20</v></c>

and every other cell in the run carries a back-reference with NO TEXT:

    <c r="C3"><f t="shared" si="0"/><v>30</v></c>

Read naively, C3 has "a formula whose text is empty", which evaluates to
#VALUE!. Because xlsx.recalc writes evaluated values back, that CORRUPTED real
workbooks -- measured at 171 cells on the first corpus file tried.

Not a rare shape: 61.0% of formula-bearing workbooks in the Enron corpus use
shared formulas, and 13.2M of 20.7M formula cells are continuations
(docs/xlsx_design.md §13.J).

WHY THIS FIXTURE IS HAND-WRITTEN RATHER THAN GENERATED BY A SPREADSHEET. The
whole point is the on-disk encoding, and no writer can be relied on to choose
the shared form for a given sheet. Writing the XML directly guarantees the
shape under test is actually present.

Each column isolates one thing the translation must get right:

  C  =A2*$B$1     relative ref SHIFTS, absolute ref does NOT
  D  =A2&"A1"     a reference-looking substring inside a STRING must not shift
  E  =$A2+A$1     mixed anchoring: each half independent
  F  =SUM(A2:A3)  a RANGE, both endpoints shift
  G  =A2          a bare reference, the minimal case

Cached values are computed here in Python from the same arithmetic Excel would
do, so `xlsx.check` over this fixture measures self-consistency; the true-oracle
evidence for shared formulas is the corpus run recorded in §13.J.
"""
import zipfile, os

B1 = 10                      # the absolute anchor
A = {r: r for r in range(1, 7)}   # A1..A6 hold their own row number

rows = []
rows.append(f'<row r="1"><c r="A1"><v>{A[1]}</v></c><c r="B1"><v>{B1}</v></c></row>')

def cell(col, r, master_text=None, si=None, ref=None, value=None, t=None):
    ta = f' t="{t}"' if t else ''
    if master_text is not None:
        f = f'<f t="shared" ref="{ref}" si="{si}">{master_text}</f>'
    else:
        f = f'<f t="shared" si="{si}"/>'
    return f'<c r="{col}{r}"{ta}>{f}<v>{value}</v></c>'

for r in range(2, 7):
    first = (r == 2)
    cs = [f'<c r="A{r}"><v>{A[r]}</v></c>']
    cs.append(cell('C', r, 'A%d*$B$1' % r if first else None, 0, 'C2:C6', A[r] * B1))
    cs.append(cell('D', r, 'A%d&amp;"A1"' % r if first else None, 1, 'D2:D6',
                   f'{A[r]}A1', t='str'))
    cs.append(cell('E', r, '$A%d+A$1' % r if first else None, 2, 'E2:E6', A[r] + A[1]))
    nxt = A.get(r + 1, 0)
    cs.append(cell('F', r, 'SUM(A%d:A%d)' % (r, r + 1) if first else None, 3, 'F2:F6',
                   A[r] + nxt))
    cs.append(cell('G', r, 'A%d' % r if first else None, 4, 'G2:G6', A[r]))
    rows.append(f'<row r="{r}">' + ''.join(cs) + '</row>')

parts = {}
parts['[Content_Types].xml'] = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
    '<Default Extension="xml" ContentType="application/xml"/>'
    '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
    '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
    '</Types>')
parts['_rels/.rels'] = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
    '</Relationships>')
parts['xl/workbook.xml'] = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
    '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
    'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'
    '<sheet name="Filled" sheetId="1" r:id="rId1"/>'
    '</sheets></workbook>')
parts['xl/_rels/workbook.xml.rels'] = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
    '</Relationships>')
parts['xl/worksheets/sheet1.xml'] = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
    '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
    '<sheetData>' + ''.join(rows) + '</sheetData></worksheet>')

out = os.path.join(os.path.dirname(__file__), '..', 'examples', 'fixtures', 'xlsx', 'shared.xlsx')
out = os.path.normpath(out)
os.makedirs(os.path.dirname(out), exist_ok=True)
with zipfile.ZipFile(out, 'w', zipfile.ZIP_DEFLATED) as z:
    for name, body in parts.items():
        z.writestr(name, body)
print("wrote", out, os.path.getsize(out), "bytes,", len(parts), "parts")
